server:
  port: 8086

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/